### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter

### ISSUE THREAD

**Issue by m4mm0n** [OlympicCode/vHackOSBot-Java#3] opened 2018-03-18 07:06 UTC
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
        at net.olympiccode.vhackos.api.utils.Encryption.md5Hash(Encryption.java:15)
        at net.olympiccode.vhackos.api.requests.Route.compile(Route.java:59)
        at net.olympiccode.vhackos.api.entities.impl.vHackOSAPIImpl.verifyDetails(vHackOSAPIImpl.java:74)
        at net.olympiccode.vhackos.api.entities.impl.vHackOSAPIImpl.login(vHackOSAPIImpl.java:68)
        at net.olympiccode.vhackos.api.vHackOSAPIBuilder.buildAsync(vHackOSAPIBuilder.java:69)
        at net.olympiccode.vhackos.api.vHackOSAPIBuilder.buildBlocking(vHackOSAPIBuilder.java:78)
        at net.olympiccode.vhackos.bot.core.vHackOSBot.run(vHackOSBot.java:94)
        at net.olympiccode.vhackos.bot.core.vHackOSBot.main(vHackOSBot.java:41)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 8 more

On latest release (DC: 17th March)

**Comment by itsfolf** [comment] 2018-03-18 11:01
Duplicate of #1
Java 9 is currently not working with the bot, for now you will need to add the required module using this command `java -jar --add-modules java.xml.bind vHackOSBot.jar`

**Closed as completed** 2018-03-18 11:01 UTC
Labels: duplicate
