### ISSUE TITLE
Exception in thread "main" 

### ISSUE THREAD

**Issue by Raz0q** [OlympicCode/vHackOSBot-Java#10] opened 2018-03-29 20:18 UTC
Hello, when I edited the config file with Username and Password I get following code:

I am running ./run.sh with correct permissions, what's the error here?
Tested on Arch Linux.

> 22:14:26 INFO [vHackOSBot-Config] Creating ConfigFile...
22:14:26 INFO [vHackOSBot-ConfigAdv] Creating ConfigFile...
22:14:26 INFO [UpdateService] Creating UpdateService...
22:14:26 INFO [MiscService] Creating MiscService...
22:14:26 INFO [NetworkingService] Creating NetworkingService...
22:14:26 WARN [io.sentry.DefaultSentryClientFactory] No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames
22:14:26 WARN [io.sentry.DefaultSentryClientFactory] No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames
22:14:26 INFO [vHackOSBot-ConfigAdv] Loading advanced config...
22:14:26 INFO [vHackOSBot-ConfigAdv] Loaded advanced config in 188ms.
22:14:26 INFO [vHackOSBot-ConfigAdv] Saving advanced config...
22:14:26 INFO [vHackOSBot-ConfigAdv] Saved advanced config in 19ms.
22:14:26 INFO [vHackOSBot-Config] Loading config...
22:14:26 INFO [vHackOSBot-Config] Loaded config in 58ms.
22:14:26 INFO [vHackOSBot-Config] Saving config...
22:14:26 INFO [vHackOSBot-Config] Saved config in 0ms.
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
        at net.olympiccode.vhackos.api.utils.Encryption.md5Hash(Encryption.java:15)
        at net.olympiccode.vhackos.api.requests.Route.compile(Route.java:59)
        at net.olympiccode.vhackos.api.entities.impl.vHackOSAPIImpl.verifyDetails(vHackOSAPIImpl.java:104)
        at net.olympiccode.vhackos.api.entities.impl.vHackOSAPIImpl.login(vHackOSAPIImpl.java:79)
        at net.olympiccode.vhackos.api.vHackOSAPIBuilder.buildAsync(vHackOSAPIBuilder.java:80)
        at net.olympiccode.vhackos.api.vHackOSAPIBuilder.buildBlocking(vHackOSAPIBuilder.java:92)
        at net.olympiccode.vhackos.bot.core.vHackOSBot.run(vHackOSBot.java:102)
        at net.olympiccode.vhackos.bot.core.vHackOSBot.main(vHackOSBot.java:46)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 8 more
22:14:26 INFO [vHackOSBot] Shutting down...
22:14:26 INFO [vHackOSBot-Config] Saving config...
22:14:26 INFO [vHackOSBot-Config] Saved config in 1ms.
22:14:26 INFO [vHackOSBot-ConfigAdv] Saving advanced config...
22:14:26 INFO [vHackOSBot-ConfigAdv] Saved advanced config in 1ms.
22:14:27 WARN [io.sentry.connection.AsyncConnection] Graceful shutdown took too much time, forcing the shutdown.
22:14:27 WARN [io.sentry.connection.AsyncConnection] 0 tasks failed to execute before shutdown.

>

**Comment by itsfolf** [comment] 2018-03-29 20:21
Duplicate of #1 

Java 9 is currently not supported, for now, replace the run.sh script to `java -jar --add-modules java.xml.bind vHackOSBot.jar`.

**Comment by Raz0q** [comment] 2018-03-29 20:25
Thanks, before I was reading your answer, I removed JDK9 and replaced it with JDK8, worked flawless.

**Closed as completed** 2018-03-29 20:26 UTC
Labels: duplicate
